# Generated by Django 5.1.3 on 2024-12-01 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit', models.CharField(help_text='Введите название вашей привычки', max_length=100, verbose_name='Название привычки')),
                ('place', models.CharField(blank=True, help_text='Введите место выполнения вашей привычки', max_length=100, null=True, verbose_name='Место выполнения')),
                ('time', models.TimeField(blank=True, help_text='Введите время, когда будет вцыполнятся ваша привычка', null=True, verbose_name='Время')),
                ('sign_of_nice_habit', models.BooleanField(default=False, help_text='Укажите, является ли ваша привычка хорошей', verbose_name='Признак хорошей привычки')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], default='daily', help_text='Введите периодичность выполнения вашей привычки', max_length=100, verbose_name='Периодичность выполнения')),
                ('reward', models.CharField(blank=True, help_text='Введите награду за выполнение вашей привычки', max_length=100, null=True, verbose_name='Награда за выполнение')),
                ('time_to_complete', models.TimeField(blank=True, help_text='Введите время выполнения вашей привычки', null=True, verbose_name='Время выполнения')),
                ('sign_of_publicity', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', help_text='Введите признак публичности вашей привычки', max_length=100, verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, help_text='Выберите связанную привычку', null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habits', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
